# Generated by Django 3.2.4 on 2021-06-14 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_man', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='book_borrowed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lib_man.book'),
            preserve_default=False,
        ),
    ]
