# Generated by Django 3.2.4 on 2021-06-14 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_man', '0002_borrower_book_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='date_borrowed',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='borrower',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 9, 12, 26, 954556)),
        ),
    ]
