# Generated by Django 3.2.4 on 2021-06-16 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_man', '0003_auto_20210614_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 18, 34, 7, 776228)),
        ),
    ]
