# Generated by Django 3.2.4 on 2022-02-02 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_man', '0008_alter_borrower_date_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='_class',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='borrower',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 20, 4, 44, 976883)),
        ),
    ]
