# Generated by Django 3.2.4 on 2022-02-07 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_man', '0010_auto_20220206_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2022, 2, 22, 18, 45, 8, 2159)),
        ),
    ]
